# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: arm64v8/postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: norkom098
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - /tmp/docker:/tmp/docker
      - /tmp/postgresql/data:/var/lib/postgresql/data

  tomcat:
    image: arm64v8/tomcat:9-jdk11-corretto
    restart: always    
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /tmp/docker:/tmp/docker
      - /tmp/tomcat/webapps:/usr/local/tomcat/webapps      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080